#!/bin/bash
pip install bash_kernel 
python -m bash_kernel.install

git clone https://github.com/mrirecon/bart/
cd bart
git checkout v0.6.00
PARALLEL=1 make

cd ..

git clone https://github.com/mrirecon/view/
cd view
git checkout 6ffa45661fda405b1ecc64328721695828218b11
PARALLEL=1 TOOLBOX_PATH=../bart  make cfl2png

